import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { 
  getFirestore, 
  collection, 
  getDocs, 
  doc, 
  setDoc, 
  deleteDoc, 
  writeBatch, 
  Firestore,
  query,
  orderBy,
  limit
} from 'firebase/firestore';
import { Family, AttendanceRecord, AuditLog, ChurchUser } from '../types';

export interface FirebaseConfig {
  apiKey: string;
  authDomain: string;
  projectId: string;
  storageBucket?: string;
  messagingSenderId?: string;
  appId: string;
  measurementId?: string;
}

// Retrieve config from Vercel system Environment Variables, Local Browser Storage, or the live provisioned Firebase project
export const getFirebaseConfig = (): FirebaseConfig | null => {
  const metaEnv = (import.meta as any).env || {};
  
  // Option 1: Live provisioned Cloud Project (Auto-generated by AI Studio)
  const defaultLiveConfig: FirebaseConfig = {
    apiKey: "AIzaSyAtisIJUdvibyrI49rS5O-Ki4cxd_ZjJqU",
    authDomain: "impressive-hangout-r71nt.firebaseapp.com",
    projectId: "impressive-hangout-r71nt",
    storageBucket: "impressive-hangout-r71nt.firebasestorage.app",
    messagingSenderId: "191146276382",
    appId: "1:191146276382:web:f8d5d4797d8cca96c8200f"
  };

  // Option 2: Env variable stringified JSON configuration
  const envConfigStr = metaEnv.VITE_FIREBASE_CONFIG;
  if (envConfigStr) {
    try {
      return JSON.parse(envConfigStr);
    } catch (e) {
      console.warn('[FirebaseSync] Failed to parse VITE_FIREBASE_CONFIG env:', e);
    }
  }

  // Option 3: Individual environment variables
  if (metaEnv.VITE_FIREBASE_API_KEY && metaEnv.VITE_FIREBASE_PROJECT_ID) {
    return {
      apiKey: metaEnv.VITE_FIREBASE_API_KEY,
      authDomain: metaEnv.VITE_FIREBASE_AUTH_DOMAIN || `${metaEnv.VITE_FIREBASE_PROJECT_ID}.firebaseapp.com`,
      projectId: metaEnv.VITE_FIREBASE_PROJECT_ID,
      storageBucket: metaEnv.VITE_FIREBASE_STORAGE_BUCKET || `${metaEnv.VITE_FIREBASE_PROJECT_ID}.appspot.com`,
      messagingSenderId: metaEnv.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: metaEnv.VITE_FIREBASE_APP_ID || '',
    };
  }

  // Option 4: User custom configuration entered on the UI
  const customConfigStr = localStorage.getItem('church_firebase_config_custom');
  if (customConfigStr) {
    try {
      return JSON.parse(customConfigStr);
    } catch (e) {
      console.warn('[FirebaseSync] Failed to parse custom UI firebase config:', e);
    }
  }

  // Fallback to our pre-provisioned live database so it works out-of-the-box on every device
  return defaultLiveConfig;
};

// Returns if Firebase setup is present
export const isFirebaseConfigured = (): boolean => {
  return getFirebaseConfig() !== null;
};

let firebaseAppInstance: FirebaseApp | null = null;
let firestoreInstance: Firestore | null = null;

export const getFirestoreDb = (): Firestore | null => {
  if (firestoreInstance) return firestoreInstance;

  const config = getFirebaseConfig();
  if (!config) return null;

  try {
    if (getApps().length === 0) {
      firebaseAppInstance = initializeApp(config);
    } else {
      firebaseAppInstance = getApp();
    }
    firestoreInstance = getFirestore(firebaseAppInstance);
    return firestoreInstance;
  } catch (error) {
    console.error('[FirebaseSync] Initialization error:', error);
    return null;
  }
};

// ---------------------- DATABASE CRUDS (FIRESTORE SYNC) ----------------------

export const fetchFamiliesFromFirebase = async (): Promise<Family[]> => {
  const db = getFirestoreDb();
  if (!db) return [];
  try {
    const q = query(collection(db, 'families'), orderBy('husbandName', 'asc'));
    const snapshot = await getDocs(q);
    const list: Family[] = [];
    snapshot.forEach((snapDoc) => {
      list.push({ ...snapDoc.data(), id: snapDoc.id } as Family);
    });
    return list;
  } catch (err) {
    console.error('[FirebaseSync] Error fetching families:', err);
    throw err;
  }
};

export const fetchAttendanceFromFirebase = async (): Promise<AttendanceRecord[]> => {
  const db = getFirestoreDb();
  if (!db) return [];
  try {
    const q = query(collection(db, 'attendance'), orderBy('date', 'desc'));
    const snapshot = await getDocs(q);
    const list: AttendanceRecord[] = [];
    snapshot.forEach((snapDoc) => {
      list.push(snapDoc.data() as AttendanceRecord);
    });
    return list;
  } catch (err) {
    console.error('[FirebaseSync] Error fetching attendance:', err);
    throw err;
  }
};

export const fetchAuditLogsFromFirebase = async (): Promise<AuditLog[]> => {
  const db = getFirestoreDb();
  if (!db) return [];
  try {
    const q = query(collection(db, 'auditLogs'), orderBy('timestamp', 'desc'), limit(150));
    const snapshot = await getDocs(q);
    const list: AuditLog[] = [];
    snapshot.forEach((snapDoc) => {
      list.push({ ...snapDoc.data(), id: snapDoc.id } as AuditLog);
    });
    return list;
  } catch (err) {
    console.error('[FirebaseSync] Error fetching audit logs:', err);
    throw err;
  }
};

export const fetchUsersFromFirebase = async (): Promise<ChurchUser[]> => {
  const db = getFirestoreDb();
  if (!db) return [];
  try {
    const snapshot = await getDocs(collection(db, 'users'));
    const list: ChurchUser[] = [];
    snapshot.forEach((snapDoc) => {
      list.push(snapDoc.data() as ChurchUser);
    });
    return list;
  } catch (err) {
    console.error('[FirebaseSync] Error fetching users:', err);
    throw err;
  }
};

// Saves a single family
export const saveFamilyToFirebase = async (family: Family): Promise<void> => {
  const db = getFirestoreDb();
  if (!db) return;
  try {
    const docRef = doc(db, 'families', family.id);
    await setDoc(docRef, family);
  } catch (err) {
    console.error('[FirebaseSync] Fail to set family:', err);
    throw err;
  }
};

// Deletes a single family
export const deleteFamilyFromFirebase = async (id: string): Promise<void> => {
  const db = getFirestoreDb();
  if (!db) return;
  try {
    await deleteDoc(doc(db, 'families', id));
  } catch (err) {
    console.error('[FirebaseSync] Fail to delete family:', err);
    throw err;
  }
};

// Saves an attendance record
export const saveAttendanceToFirebase = async (record: AttendanceRecord): Promise<void> => {
  const db = getFirestoreDb();
  if (!db) return;
  try {
    // We use date as the document key to enforce uniqueness per day and avoid duplicate entries
    const docRef = doc(db, 'attendance', record.date);
    await setDoc(docRef, record);
  } catch (err) {
    console.error('[FirebaseSync] Fail to set attendance:', err);
    throw err;
  }
};

// Saves an audit log
export const saveAuditLogToFirebase = async (log: AuditLog): Promise<void> => {
  const db = getFirestoreDb();
  if (!db) return;
  try {
    const docRef = doc(db, 'auditLogs', log.id);
    await setDoc(docRef, log);
  } catch (err) {
    console.error('[FirebaseSync] Fail to set log:', err);
    throw err;
  }
};

// Saves a user profile
export const saveUserToFirebase = async (user: ChurchUser): Promise<void> => {
  const db = getFirestoreDb();
  if (!db) return;
  try {
    // Use email as key
    const safeEmailKey = user.email.replace(/\./g, '_');
    const docRef = doc(db, 'users', safeEmailKey);
    await setDoc(docRef, user);
  } catch (err) {
    console.error('[FirebaseSync] Fail to set user:', err);
    throw err;
  }
};

// Push all local data to the Firebase cloud (used during first setup migration)
export const migrateLocalToFirebase = async (
  families: Family[], 
  attendance: AttendanceRecord[], 
  auditLogs: AuditLog[], 
  users: ChurchUser[]
): Promise<{ success: boolean; count: number; error?: string }> => {
  const db = getFirestoreDb();
  if (!db) return { success: false, count: 0, error: 'Firebase is not initialized.' };

  try {
    let count = 0;

    // We migrate families in sequential batches of 100 to avoid Firestore limits
    for (const fam of families) {
      await saveFamilyToFirebase(fam);
      count++;
    }

    for (const att of attendance) {
      await saveAttendanceToFirebase(att);
      count++;
    }

    for (const log of auditLogs) {
      await saveAuditLogToFirebase(log);
      count++;
    }

    for (const usr of users) {
      await saveUserToFirebase(usr);
      count++;
    }

    return { success: true, count };
  } catch (err: any) {
    console.error('[FirebaseSync] Bulk Sync Migration failure:', err);
    return { success: false, error: err.message || String(err), count: 0 };
  }
};
