import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { 
  getFirestore, 
  collection, 
  getDocs, 
  doc, 
  setDoc, 
  deleteDoc, 
  Firestore,
  query,
  orderBy,
  limit
} from 'firebase/firestore';
import { Family, AttendanceRecord, AuditLog, ChurchUser } from '../types';
import { safeLocalStorage } from './safeStorage';

export interface FirebaseConfig {
  apiKey: string;
  authDomain: string;
  projectId: string;
  storageBucket?: string;
  messagingSenderId?: string;
  appId: string;
  measurementId?: string;
  firestoreDatabaseId?: string;
}

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: {
      providerId?: string | null;
      email?: string | null;
    }[];
  }
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null): never {
  let currentUser: any = null;
  try {
    const auth = getAuth();
    currentUser = auth.currentUser;
  } catch (e) {
    // Ignore if Auth is not yet initialized or fails to resolve
  }

  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: currentUser?.uid || null,
      email: currentUser?.email || null,
      emailVerified: currentUser?.emailVerified || null,
      isAnonymous: currentUser?.isAnonymous || null,
      tenantId: currentUser?.tenantId || null,
      providerInfo: currentUser?.providerData?.map((provider: any) => ({
        providerId: provider.providerId,
        email: provider.email,
      })) || []
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

// Timeout utility for making sure Firebase never hangs the application indefinitely
const withTimeout = <T>(promise: Promise<T>, timeoutMs: number = 6000): Promise<T> => {
  return Promise.race([
    promise,
    new Promise<never>((_, reject) => 
      setTimeout(() => reject(new Error('Firebase Request Timeout (6s)')), timeoutMs)
    )
  ]);
};

// Retrieve config from Vercel system Environment Variables, Local Browser Storage, or the live provisioned Firebase project
export const getFirebaseConfig = (): FirebaseConfig | null => {
  const metaEnv = (import.meta as any).env || {};
  
  // Option 1: Live provisioned Cloud Project (Auto-generated by AI Studio)
  const defaultLiveConfig: FirebaseConfig = {
    apiKey: "AIzaSyAtisIJUdvibyrI49rS5O-Ki4cxd_ZjJqU",
    authDomain: "impressive-hangout-r71nt.firebaseapp.com",
    projectId: "impressive-hangout-r71nt",
    storageBucket: "impressive-hangout-r71nt.firebasestorage.app",
    messagingSenderId: "191146276382",
    appId: "1:191146276382:web:f8d5d4797d8cca96c8200f",
    firestoreDatabaseId: "ai-studio-c82cfa66-a4b0-4ca2-b17d-3c433d16c035"
  };

  // Option 2: Env variable stringified JSON configuration
  const envConfigStr = metaEnv.VITE_FIREBASE_CONFIG;
  if (envConfigStr) {
    try {
      return JSON.parse(envConfigStr);
    } catch (e) {
      console.warn('[FirebaseSync] Failed to parse VITE_FIREBASE_CONFIG env:', e);
    }
  }

  // Option 3: Individual environment variables
  if (metaEnv.VITE_FIREBASE_API_KEY && metaEnv.VITE_FIREBASE_PROJECT_ID) {
    return {
      apiKey: metaEnv.VITE_FIREBASE_API_KEY,
      authDomain: metaEnv.VITE_FIREBASE_AUTH_DOMAIN || `${metaEnv.VITE_FIREBASE_PROJECT_ID}.firebaseapp.com`,
      projectId: metaEnv.VITE_FIREBASE_PROJECT_ID,
      storageBucket: metaEnv.VITE_FIREBASE_STORAGE_BUCKET || `${metaEnv.VITE_FIREBASE_PROJECT_ID}.appspot.com`,
      messagingSenderId: metaEnv.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: metaEnv.VITE_FIREBASE_APP_ID || '',
      firestoreDatabaseId: metaEnv.VITE_FIREBASE_DATABASE_ID,
    };
  }

  // Option 4: User custom configuration entered on the UI
  const customConfigStr = safeLocalStorage.getItem('church_firebase_config_custom');
  if (customConfigStr) {
    try {
      return JSON.parse(customConfigStr);
    } catch (e) {
      console.warn('[FirebaseSync] Failed to parse custom UI firebase config:', e);
    }
  }

  // Fallback to our pre-provisioned live database so it works out-of-the-box on every device
  return defaultLiveConfig;
};

// Returns if Firebase setup is present
export const isFirebaseConfigured = (): boolean => {
  return getFirebaseConfig() !== null;
};

let firebaseAppInstance: FirebaseApp | null = null;
let firestoreInstance: Firestore | null = null;

export const getFirestoreDb = (): Firestore | null => {
  if (firestoreInstance) return firestoreInstance;

  const config = getFirebaseConfig();
  if (!config) return null;

  try {
    if (getApps().length === 0) {
      firebaseAppInstance = initializeApp(config);
    } else {
      firebaseAppInstance = getApp();
    }
    
    if (config.firestoreDatabaseId) {
      firestoreInstance = getFirestore(firebaseAppInstance, config.firestoreDatabaseId);
    } else {
      firestoreInstance = getFirestore(firebaseAppInstance);
    }
    return firestoreInstance;
  } catch (error) {
    console.error('[FirebaseSync] Initialization error:', error);
    return null;
  }
};

// ---------------------- DATABASE CRUDS (FIRESTORE SYNC) ----------------------

export const fetchFamiliesFromFirebase = async (): Promise<Family[]> => {
  const db = getFirestoreDb();
  if (!db) return [];
  const colPath = 'families';
  try {
    const q = query(collection(db, colPath), orderBy('husbandName', 'asc'));
    const snapshot = await withTimeout(getDocs(q));
    const list: Family[] = [];
    snapshot.forEach((snapDoc) => {
      list.push({ ...snapDoc.data(), id: snapDoc.id } as Family);
    });
    return list;
  } catch (err: any) {
    if (err.message && err.message.includes('Timeout')) {
       console.error('[FirebaseSync] Timeout error fetching families:', err);
       throw err;
    }
    handleFirestoreError(err, OperationType.GET, colPath);
  }
};

export const fetchAttendanceFromFirebase = async (): Promise<AttendanceRecord[]> => {
  const db = getFirestoreDb();
  if (!db) return [];
  const colPath = 'attendance';
  try {
    const q = query(collection(db, colPath), orderBy('date', 'desc'));
    const snapshot = await withTimeout(getDocs(q));
    const list: AttendanceRecord[] = [];
    snapshot.forEach((snapDoc) => {
      list.push(snapDoc.data() as AttendanceRecord);
    });
    return list;
  } catch (err: any) {
    if (err.message && err.message.includes('Timeout')) {
       console.error('[FirebaseSync] Timeout error fetching attendance:', err);
       throw err;
    }
    handleFirestoreError(err, OperationType.GET, colPath);
  }
};

export const fetchAuditLogsFromFirebase = async (): Promise<AuditLog[]> => {
  const db = getFirestoreDb();
  if (!db) return [];
  const colPath = 'auditLogs';
  try {
    const q = query(collection(db, colPath), orderBy('timestamp', 'desc'), limit(150));
    const snapshot = await withTimeout(getDocs(q));
    const list: AuditLog[] = [];
    snapshot.forEach((snapDoc) => {
      list.push({ ...snapDoc.data(), id: snapDoc.id } as AuditLog);
    });
    return list;
  } catch (err: any) {
    if (err.message && err.message.includes('Timeout')) {
       console.error('[FirebaseSync] Timeout error fetching audit logs:', err);
       throw err;
    }
    handleFirestoreError(err, OperationType.GET, colPath);
  }
};

export const fetchUsersFromFirebase = async (): Promise<ChurchUser[]> => {
  const db = getFirestoreDb();
  if (!db) return [];
  const colPath = 'users';
  try {
    const snapshot = await withTimeout(getDocs(collection(db, colPath)));
    const list: ChurchUser[] = [];
    snapshot.forEach((snapDoc) => {
      list.push(snapDoc.data() as ChurchUser);
    });
    return list;
  } catch (err: any) {
    if (err.message && err.message.includes('Timeout')) {
       console.error('[FirebaseSync] Timeout error fetching users:', err);
       throw err;
    }
    handleFirestoreError(err, OperationType.GET, colPath);
  }
};

// Saves a single family
export const saveFamilyToFirebase = async (family: Family): Promise<void> => {
  const db = getFirestoreDb();
  if (!db) return;
  const path = `families/${family.id}`;
  try {
    const docRef = doc(db, 'families', family.id);
    await withTimeout(setDoc(docRef, family));
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, path);
  }
};

// Deletes a single family
export const deleteFamilyFromFirebase = async (id: string): Promise<void> => {
  const db = getFirestoreDb();
  if (!db) return;
  const path = `families/${id}`;
  try {
    await withTimeout(deleteDoc(doc(db, 'families', id)));
  } catch (err) {
    handleFirestoreError(err, OperationType.DELETE, path);
  }
};

// Saves an attendance record
export const saveAttendanceToFirebase = async (record: AttendanceRecord): Promise<void> => {
  const db = getFirestoreDb();
  if (!db) return;
  const path = `attendance/${record.date}`;
  try {
    // We use date as the document key to enforce uniqueness per day and avoid duplicate entries
    const docRef = doc(db, 'attendance', record.date);
    await withTimeout(setDoc(docRef, record));
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, path);
  }
};

// Saves an audit log
export const saveAuditLogToFirebase = async (log: AuditLog): Promise<void> => {
  const db = getFirestoreDb();
  if (!db) return;
  const path = `auditLogs/${log.id}`;
  try {
    const docRef = doc(db, 'auditLogs', log.id);
    await withTimeout(setDoc(docRef, log));
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, path);
  }
};

// Saves a user profile
export const saveUserToFirebase = async (user: ChurchUser): Promise<void> => {
  const db = getFirestoreDb();
  if (!db) return;
  const safeEmailKey = user.email.replace(/\./g, '_');
  const path = `users/${safeEmailKey}`;
  try {
    const docRef = doc(db, 'users', safeEmailKey);
    await withTimeout(setDoc(docRef, user));
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, path);
  }
};

// Push all local data to the Firebase cloud (used during first setup migration)
export const migrateLocalToFirebase = async (
  families: Family[], 
  attendance: AttendanceRecord[], 
  auditLogs: AuditLog[], 
  users: ChurchUser[]
): Promise<{ success: boolean; count: number; error?: string }> => {
  const db = getFirestoreDb();
  if (!db) return { success: false, count: 0, error: 'Firebase is not initialized.' };

  try {
    let count = 0;

    // We migrate families in sequential batches of 100 to avoid Firestore limits
    for (const fam of families) {
      await saveFamilyToFirebase(fam);
      count++;
    }

    for (const att of attendance) {
      await saveAttendanceToFirebase(att);
      count++;
    }

    for (const log of auditLogs) {
      await saveAuditLogToFirebase(log);
      count++;
    }

    for (const usr of users) {
      await saveUserToFirebase(usr);
      count++;
    }

    return { success: true, count };
  } catch (err: any) {
    console.error('[FirebaseSync] Bulk Sync Migration failure:', err);
    return { success: false, error: err.message || String(err), count: 0 };
  }
};
